# Generated by Django 3.0.8 on 2020-08-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbell',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('photo', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('condition', models.CharField(max_length=10)),
                ('available', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'barbell',
            },
        ),
    ]
